<Project>

  <PropertyGroup>    
    <Version>0.1.1</Version>
    <Authors>Toralux</Authors>
    <PackageTags>Open IdentityServer Admin OpenIDConnect OAuth2 Identity</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>nuget-icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/toralux/Open.IdentityServer.Admin</PackageProjectUrl>
    <RepositoryUrl>https://github.com/toralux/Open.IdentityServer.Admin</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>


  <ItemGroup>
    <None Include="../../docs/Images/nuget-icon.png" Pack="true" Visible="false" PackagePath="" />
    <None Include="../../LICENSE" Pack="true" PackagePath="" />
    <None Include="../../README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
