<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Entity Framework configuration for the administration of the Open IdentityServer and Asp.Net Core Identity</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="Skoruba.AuditLogging.EntityFramework" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Toralux.Open.IdentityServer.Admin.EntityFramework.Identity\Toralux.Open.IdentityServer.Admin.EntityFramework.Identity.csproj" />
		<ProjectReference Include="..\Toralux.Open.IdentityServer.Admin.EntityFramework.Admin.Storage\Toralux.Open.IdentityServer.Admin.EntityFramework.Admin.Storage.csproj" />
	</ItemGroup>

</Project>






