import { SnippetLanguage } from "@/lib/highlight/highlightCode";

/**
 * Generates the .NET 10 wire-up for a client, derived from the values currently
 * in the client form. The functions here are pure - the tab passes a snapshot
 * in and renders whatever comes out, so the snippets follow unsaved edits.
 *
 * Only the code flow and client credentials scenarios are supported.
 */

/** Scopes that only make sense for a user-facing flow. */
const IDENTITY_ONLY_SCOPES = new Set([
  "openid",
  "profile",
  "email",
  "address",
  "phone",
  "roles",
  "offline_access",
]);

export type SnippetClientConfig = {
  clientId: string;
  scopes: string[];
  requireClientSecret: boolean;
  requirePkce: boolean;
  allowOfflineAccess: boolean;
  requirePushedAuthorization: boolean;
  requireDPoP: boolean;
  redirectUris: string[];
  postLogoutRedirectUris: string[];
};

/**
 * How the application proves its identity at the token endpoint. With JWK
 * client secrets out of the fork's scope, the shared secret is the only
 * supported authentication.
 */
export type ClientAuthentication = "shared_secret";

export type SnippetOptions = {
  /** Base address of IdentityServer, e.g. https://localhost:44310 */
  authority: string;
  /** Used for the cookie, the token client and the HttpClient names. */
  appName: string;
  /** Base address of the API the application calls. */
  apiBaseUrl: string;
  /** Read the credential from configuration instead of inlining it in the code. */
  useUserSecrets: boolean;
  clientAuthentication: ClientAuthentication;
};

/** A translatable note rendered below the code of a step. */
export type SnippetMessage = {
  key: string;
  values?: Record<string, string>;
};

export type SnippetBlock = {
  id: string;
  language: SnippetLanguage;
  code: string;
  /** Shown in the block header and used as the download name. */
  fileName?: string;
  isDownloadable?: boolean;
};

export type SnippetStep = {
  id: string;
  titleKey: string;
  descriptionKey?: string;
  blocks: SnippetBlock[];
  notes?: SnippetMessage[];
  warnings?: SnippetMessage[];
};

export type SnippetDocument = {
  steps: SnippetStep[];
};

const PACKAGE_OIDC = "Microsoft.AspNetCore.Authentication.OpenIdConnect";
const PACKAGE_ATM = "Duende.AccessTokenManagement";
const PACKAGE_ATM_OIDC = "Duende.AccessTokenManagement.OpenIdConnect";

/** Configuration section per scenario, so both snippets can live side by side. */
const OIDC_SECTION = "Oidc";
const CLIENT_CREDENTIALS_SECTION = "ClientCredentials";

const secretKey = (section: string) => `${section}:ClientSecret`;
const dPoPKey = (section: string) => `${section}:DPoPJsonWebKey`;
const authorityKey = (section: string) => `${section}:Authority`;
const clientIdKey = (section: string) => `${section}:ClientId`;

/** `builder.Configuration["Section:Key"]` as it appears in Program.cs. */
const configuration = (key: string) =>
  `builder.Configuration[${csharpString(key)}]`;

/** Name of the registered HttpClient - it stands for the API being called. */
const API_HTTP_CLIENT_NAME = "api";

/** ASP.NET Core defaults - a snippet that restates them only adds noise. */
const DEFAULT_CALLBACK_PATH = "/signin-oidc";
const DEFAULT_SIGNED_OUT_CALLBACK_PATH = "/signout-callback-oidc";

const SECRET_PLACEHOLDER = "<your client secret>";
const DPOP_KEY_PLACEHOLDER = "<a private JWK generated by this application>";

/**
 * Windows PowerShell 5.1 strips the double quotes of a JSON argument handed to a
 * native command, which leaves a key that no longer parses at startup.
 */
const JSON_SHELL_QUOTING_COMMENT =
  '# Windows PowerShell 5.1 drops the double quotes inside the JSON - escape them as \\" there, or use PowerShell 7, cmd or bash';

/**
 * Everything outside printable ASCII is written as \uXXXX. A NUL or one of the
 * other C# line terminators (U+0085, U+2028, U+2029) would break the literal.
 */
export const csharpString = (value: string) =>
  `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")
    .replace(
      /[^\x20-\x7e]/g,
      (char) => `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`,
    )}"`;

/** Trailing slashes break `new Uri(base)` + relative path composition. */
const trimTrailingSlash = (value: string) => value.replace(/\/+$/, "");

const ensureTrailingSlash = (value: string) =>
  value.endsWith("/") ? value : `${value}/`;

/**
 * ASP.NET Core takes the callback as a path, not a full URI. The form allows
 * values that are not valid absolute URLs (yet), hence the guarded parse.
 */
const derivePath = (uris: string[], fallback: string): string => {
  for (const uri of uris) {
    try {
      const { pathname } = new URL(uri);

      if (pathname && pathname !== "/") {
        return pathname;
      }
    } catch {
      // Not an absolute URI - fall through to the next candidate.
    }
  }

  return fallback;
};

/** An API scope is one the token endpoint can put in an access token. */
const hasApiScope = (scopes: string[]): boolean =>
  scopes.some((scope) => !IDENTITY_ONLY_SCOPES.has(scope));

/**
 * Duende's access token management backs the API HttpClient, the refresh token
 * and the DPoP proof, so any of them pulls it in.
 */
const needsTokenManagement = (
  clientConfig: SnippetClientConfig,
  scopes: string[],
): boolean =>
  hasApiScope(scopes) ||
  clientConfig.allowOfflineAccess ||
  clientConfig.requireDPoP;

/**
 * Reduces a value to `[a-z0-9-]`, which both a cookie name and a named
 * HttpClient accept. Run it over whatever the user types too - a cookie name is
 * a token, so a space in it would break the sign-in without saying anything.
 */
export const toApplicationName = (value: string): string => {
  const name = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return name === "" ? "my-app" : name;
};

/**
 * Identity scopes first, API scopes after them, `offline_access` last - the
 * order the scopes are usually written by hand in.
 */
const orderScopes = (scopes: string[], allowOfflineAccess: boolean): string[] => {
  const unique = Array.from(new Set(scopes.filter((scope) => scope !== "")));

  if (allowOfflineAccess && !unique.includes("offline_access")) {
    unique.push("offline_access");
  }

  const weight = (scope: string) => {
    if (scope === "openid") return 0;
    if (scope === "profile") return 1;
    if (scope === "offline_access") return 4;

    return IDENTITY_ONLY_SCOPES.has(scope) ? 2 : 3;
  };

  return unique.sort((left, right) => weight(left) - weight(right));
};

const packageStep = (
  packages: string[],
  notes: SnippetMessage[] = [],
): SnippetStep => ({
  id: "packages",
  titleKey: "Client.Integration.Steps.Packages",
  descriptionKey: "Client.Integration.Steps.PackagesDescription",
  blocks: [
    {
      id: "packages",
      language: "bash",
      code: [
        ...packages.map((packageId) => `dotnet add package ${packageId}`),
      ].join("\n"),
    },
  ],
  notes,
});

/**
 * Authority and client id live in appsettings.json rather than in the code, so
 * Program.cs and the assertion service read the same values.
 */
const appSettingsStep = (
  section: string,
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetStep => ({
  id: "appsettings",
  titleKey: "Client.Integration.Steps.Settings",
  descriptionKey: "Client.Integration.Steps.SettingsDescription",
  blocks: [
    {
      id: "appsettings",
      language: "json",
      code: JSON.stringify(
        {
          [section]: {
            Authority: trimTrailingSlash(options.authority),
            ClientId: clientConfig.clientId,
          },
        },
        null,
        2,
      ),
      fileName: "appsettings.json",
    },
  ],
});

/**
 * The client credential, which already exists - it was created on the Secrets
 * tab, so this step only moves it into the application's user secrets.
 */
const credentialStep = (
  section: string,
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetStep | null => {
  if (!clientConfig.requireClientSecret || !options.useUserSecrets) {
    return null;
  }

  return {
    id: "credential",
    titleKey: "Client.Integration.Steps.Secret",
    descriptionKey: "Client.Integration.Steps.SecretDescription",
    blocks: [
      {
        id: "user-secrets",
        language: "bash",
        code: [
          "dotnet user-secrets init",
          `dotnet user-secrets set "${secretKey(section)}" '${SECRET_PLACEHOLDER}'`,
        ].join("\n"),
      },
    ],
    notes: [{ key: "Client.Integration.Notes.CredentialStorage" }],
  };
};

/**
 * The DPoP proof key, which does not exist yet - it belongs to the application
 * alone and is registered nowhere, so it has to be generated first.
 *
 * Where it goes follows the "keep secrets out of the code" switch, like the client
 * credential does. With user secrets the step also initialises them when no
 * credential step ran before it (a public client has none).
 */
const dPoPKeyStep = (
  section: string,
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetStep | null => {
  if (!clientConfig.requireDPoP) {
    return null;
  }

  const blocks: SnippetBlock[] = [
    {
      id: "dpop-generate",
      language: "csharp",
      code: [
        "using System.Security.Cryptography;",
        "using System.Text.Json;",
        "using Microsoft.IdentityModel.Tokens;",
        "",
        "var rsa = new RsaSecurityKey(RSA.Create(2048));",
        "var jwk = JsonWebKeyConverter.ConvertFromRSASecurityKey(rsa);",
        'jwk.Alg = "PS256";',
        "",
        "Console.WriteLine(JsonSerializer.Serialize(jwk));",
      ].join("\n"),
    },
  ];

  const notes: SnippetMessage[] = [
    { key: "Client.Integration.Notes.DPoPProofKey" },
    { key: "Client.Integration.Notes.DPoPApiSide" },
  ];

  if (options.useUserSecrets) {
    const hasCredentialStep =
      credentialStep(section, clientConfig, options) !== null;

    blocks.push({
      id: "dpop-user-secrets",
      language: "bash",
      code: [
        ...(hasCredentialStep ? [] : ["dotnet user-secrets init"]),
        JSON_SHELL_QUOTING_COMMENT,
        `dotnet user-secrets set "${dPoPKey(section)}" '${DPOP_KEY_PLACEHOLDER}'`,
      ].join("\n"),
    });
  } else {
    notes.push({ key: "Client.Integration.Notes.DPoPKeyInline" });
  }

  return {
    id: "dpop-key",
    titleKey: "Client.Integration.Steps.DPoPKey",
    descriptionKey: "Client.Integration.Steps.DPoPKeyDescription",
    blocks,
    notes,
  };
};

const secretExpression = (
  configurationKey: string,
  useUserSecrets: boolean,
): string =>
  useUserSecrets
    ? `builder.Configuration[${csharpString(configurationKey)}]`
    : csharpString(SECRET_PLACEHOLDER);

/**
 * The DPoP proof key is a private key, so unlike the shared secret it is never a
 * reasonable thing to leave in the code - the inline form exists only so the
 * generated program compiles and runs when user secrets are switched off.
 */
const dPoPKeyExpression = (section: string, useUserSecrets: boolean): string =>
  useUserSecrets
    ? `DPoPProofKey.Parse(builder.Configuration[${csharpString(dPoPKey(section))}]!)`
    : `DPoPProofKey.Parse(${csharpString(DPOP_KEY_PLACEHOLDER)})`;

const buildAuthorizationCodeProgram = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
  scopes: string[],
): string => {
  // An API scope means there is something to call with the access token.
  const useApiHttpClient = hasApiScope(scopes);

  const useTokenManagement = needsTokenManagement(clientConfig, scopes);

  const duendeUsings: string[] = [];

  if (clientConfig.requireDPoP) {
    duendeUsings.push("using Duende.AccessTokenManagement.DPoP;");
  }

  if (useTokenManagement) {
    duendeUsings.push("using Duende.AccessTokenManagement.OpenIdConnect;");
  }

  const usings = [
    ...duendeUsings,
    "using Microsoft.AspNetCore.Authentication.Cookies;",
    "using Microsoft.AspNetCore.Authentication.OpenIdConnect;",
    "using Microsoft.IdentityModel.Tokens;",
  ];

  const cookieOptions = [
    `        options.Cookie.Name = ${csharpString(`__Host-${options.appName}`)};`,
    "        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;",
    "",
    "        options.Cookie.SameSite = SameSiteMode.Strict;",
  ];

  if (clientConfig.allowOfflineAccess) {
    cookieOptions.push(
      "",
      "        options.Events.OnSigningOut = async e =>",
      "            await e.HttpContext.RevokeRefreshTokenAsync();",
    );
  }

  const oidcOptions = [
    `        options.Authority = ${configuration(authorityKey(OIDC_SECTION))};`,
    "",
    `        options.ClientId = ${configuration(clientIdKey(OIDC_SECTION))};`,
  ];

  if (clientConfig.requireClientSecret) {
    oidcOptions.push(
      `        options.ClientSecret = ${secretExpression(secretKey(OIDC_SECTION), options.useUserSecrets)};`,
    );
  }

  oidcOptions.push("", '        options.ResponseType = "code";');

  // UsePkce is never turned off, whatever the client says. A client that does not require
  // PKCE still accepts - and validates - a code challenge, so leaving the ASP.NET Core
  // default on costs nothing, while "UsePkce = false" would only weaken the copied code.

  if (clientConfig.requirePushedAuthorization) {
    oidcOptions.push(
      "        options.PushedAuthorizationBehavior = PushedAuthorizationBehavior.Require;",
    );
  }

  const callbackPath = derivePath(clientConfig.redirectUris, DEFAULT_CALLBACK_PATH);
  const signedOutCallbackPath = derivePath(
    clientConfig.postLogoutRedirectUris,
    DEFAULT_SIGNED_OUT_CALLBACK_PATH,
  );

  const callbackPaths = [
    ...(callbackPath === DEFAULT_CALLBACK_PATH
      ? []
      : [`        options.CallbackPath = ${csharpString(callbackPath)};`]),
    ...(signedOutCallbackPath === DEFAULT_SIGNED_OUT_CALLBACK_PATH
      ? []
      : [
          `        options.SignedOutCallbackPath = ${csharpString(signedOutCallbackPath)};`,
        ]),
  ];

  if (callbackPaths.length > 0) {
    oidcOptions.push(
      "",
      ...callbackPaths,
    );
  }

  oidcOptions.push(
    "",
    "        options.Scope.Clear();",
    ...scopes.map((scope) => `        options.Scope.Add(${csharpString(scope)});`),
    "",
    "        options.GetClaimsFromUserInfoEndpoint = true;",
    "        options.SaveTokens = true;",
    "        options.MapInboundClaims = false;",
    "",
    "        options.TokenValidationParameters = new TokenValidationParameters",
    "        {",
    '            NameClaimType = "name",',
    '            RoleClaimType = "role"',
    "        };",
  );

  const tokenManagement: string[] = [];

  if (useTokenManagement) {
    tokenManagement.push("");

    if (clientConfig.requireDPoP) {
      tokenManagement.push(
        "builder.Services.AddOpenIdConnectAccessTokenManagement(options =>",
        "{",
        `    options.DPoPJsonWebKey = ${dPoPKeyExpression(OIDC_SECTION, options.useUserSecrets)};`,
        "});",
      );
    } else {
      tokenManagement.push(
        "builder.Services.AddOpenIdConnectAccessTokenManagement();",
      );
    }

    if (useApiHttpClient) {
      tokenManagement.push(
        "",
        `builder.Services.AddUserAccessTokenHttpClient(${csharpString(API_HTTP_CLIENT_NAME)}, configureClient: client =>`,
        "{",
        `    client.BaseAddress = new Uri(${csharpString(ensureTrailingSlash(options.apiBaseUrl))});`,
        "});",
      );
    }
  }

  return [
    ...usings,
    "",
    "var builder = WebApplication.CreateBuilder(args);",
    "",
    "builder.Services.AddAuthentication(options =>",
    "    {",
    "        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;",
    "        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;",
    "        options.DefaultSignOutScheme = OpenIdConnectDefaults.AuthenticationScheme;",
    "    })",
    "    .AddCookie(options =>",
    "    {",
    ...cookieOptions,
    "    })",
    "    .AddOpenIdConnect(options =>",
    "    {",
    ...oidcOptions,
    "    });",
    ...tokenManagement,
    "",
    "builder.Services.AddAuthorization();",
    "",
    "var app = builder.Build();",
    "",
    "app.UseAuthentication();",
    "app.UseAuthorization();",
    "",
    "app.Run();",
  ].join("\n");
};

export const buildAuthorizationCodeSnippet = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetDocument => {
  const scopes = orderScopes(clientConfig.scopes, clientConfig.allowOfflineAccess);

  const packages = [PACKAGE_OIDC];

  if (needsTokenManagement(clientConfig, scopes)) {
    packages.push(PACKAGE_ATM_OIDC);
  }

  const packageNotes: SnippetMessage[] = [];

  const steps: SnippetStep[] = [
    packageStep(packages, packageNotes),
    appSettingsStep(OIDC_SECTION, clientConfig, options),
  ];

  const oidcSteps = [
    credentialStep(OIDC_SECTION, clientConfig, options),
    dPoPKeyStep(OIDC_SECTION, clientConfig, options),
  ].filter((step) => step !== null);

  steps.push(...oidcSteps);

  const notes: SnippetMessage[] = [];
  const warnings: SnippetMessage[] = [];

  if (!scopes.includes("openid")) {
    warnings.push({ key: "Client.Integration.Notes.MissingOpenIdScope" });
  }

  if (!clientConfig.requirePkce) {
    warnings.push({ key: "Client.Integration.Notes.PkceDisabled" });
  }

  if (!clientConfig.requireClientSecret) {
    notes.push({ key: "Client.Integration.Notes.PublicClient" });
  }

  if (clientConfig.redirectUris.length === 0) {
    warnings.push({ key: "Client.Integration.Notes.NoRedirectUri" });
  }

  if (!options.useUserSecrets && clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.InlineSecret" });
  }

  steps.push({
    id: "program",
    titleKey: "Client.Integration.Steps.Program",
    descriptionKey: "Client.Integration.Steps.ProgramDescription",
    blocks: [
      {
        id: "program",
        language: "csharp",
        code: buildAuthorizationCodeProgram(clientConfig, options, scopes),
        fileName: "Program.cs",
        isDownloadable: true,
      },
    ],
    notes,
    warnings,
  });

  return { steps };
};

const buildClientCredentialsProgram = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
  scopes: string[],
): string => {
  const usings = ["using Duende.AccessTokenManagement;"];

  if (clientConfig.requireDPoP) {
    usings.push("using Duende.AccessTokenManagement.DPoP;");
  }

  const clientOptions = [
    '        client.TokenEndpoint = new Uri($"{authority}/connect/token");',
    "",
    `        client.ClientId = ClientId.Parse(${configuration(clientIdKey(CLIENT_CREDENTIALS_SECTION))}!);`,
  ];

  if (clientConfig.requireClientSecret) {
    const secret = options.useUserSecrets
      ? `${secretExpression(secretKey(CLIENT_CREDENTIALS_SECTION), true)}!`
      : csharpString(SECRET_PLACEHOLDER);

    clientOptions.push(`        client.ClientSecret = ClientSecret.Parse(${secret});`);
  }

  if (scopes.length > 0) {
    clientOptions.push(
      "",
      `        client.Scope = Scope.Parse(${csharpString(scopes.join(" "))});`,
    );
  }

  if (clientConfig.requireDPoP) {
    clientOptions.push(
      "",
      `        client.DPoPJsonWebKey = ${dPoPKeyExpression(CLIENT_CREDENTIALS_SECTION, options.useUserSecrets)};`,
    );
  }

  return [
    ...usings,
    "",
    "var builder = Host.CreateApplicationBuilder(args);",
    "",
    `var authority = ${configuration(authorityKey(CLIENT_CREDENTIALS_SECTION))}!;`,
    "",
    "builder.Services.AddDistributedMemoryCache();",
    "",
    "builder.Services.AddClientCredentialsTokenManagement()",
    `    .AddClient(${csharpString(options.appName)}, client =>`,
    "    {",
    ...clientOptions,
    "    });",
    "",
    `builder.Services.AddClientCredentialsHttpClient(${csharpString(API_HTTP_CLIENT_NAME)},`,
    `    ClientCredentialsClientName.Parse(${csharpString(options.appName)}),`,
    "    client =>",
    "    {",
    `        client.BaseAddress = new Uri(${csharpString(ensureTrailingSlash(options.apiBaseUrl))});`,
    "    });",
    "",
    "builder.Services.AddHostedService<ApiWorker>();",
    "",
    "builder.Build().Run();",
  ].join("\n");
};

const buildClientCredentialsWorker = (): string =>
  [
    "public class ApiWorker(",
    "    IHttpClientFactory httpClientFactory,",
    "    ILogger<ApiWorker> logger) : BackgroundService",
    "{",
    "    protected override async Task ExecuteAsync(CancellationToken stoppingToken)",
    "    {",
    `        var client = httpClientFactory.CreateClient(${csharpString(API_HTTP_CLIENT_NAME)});`,
    "",
    "        while (!stoppingToken.IsCancellationRequested)",
    "        {",
    '            var response = await client.GetAsync("data", stoppingToken);',
    "",
    '            logger.LogInformation("API responded with {StatusCode}", response.StatusCode);',
    "",
    "            await Task.Delay(TimeSpan.FromMinutes(1), stoppingToken);",
    "        }",
    "    }",
    "}",
  ].join("\n");

export const buildClientCredentialsSnippet = (
  clientConfig: SnippetClientConfig,
  options: SnippetOptions,
): SnippetDocument => {
  const requestedScopes = Array.from(new Set(clientConfig.scopes));
  const scopes = requestedScopes.filter(
    (scope) => !IDENTITY_ONLY_SCOPES.has(scope),
  );
  const droppedScopes = requestedScopes.filter((scope) =>
    IDENTITY_ONLY_SCOPES.has(scope),
  );

  const steps: SnippetStep[] = [
    packageStep([PACKAGE_ATM]),
    appSettingsStep(CLIENT_CREDENTIALS_SECTION, clientConfig, options),
  ];

  const machineSteps = [
    credentialStep(CLIENT_CREDENTIALS_SECTION, clientConfig, options),
    dPoPKeyStep(CLIENT_CREDENTIALS_SECTION, clientConfig, options),
  ].filter((step) => step !== null);

  steps.push(...machineSteps);

  const notes: SnippetMessage[] = [];
  const warnings: SnippetMessage[] = [];

  if (droppedScopes.length > 0) {
    notes.push({
      key: "Client.Integration.Notes.IdentityScopesSkipped",
      values: { scopes: droppedScopes.join(", ") },
    });
  }

  if (scopes.length === 0) {
    warnings.push({ key: "Client.Integration.Notes.NoApiScope" });
  }

  if (!clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.MachineClientWithoutSecret" });
  }

  if (!options.useUserSecrets && clientConfig.requireClientSecret) {
    warnings.push({ key: "Client.Integration.Notes.InlineSecret" });
  }

  steps.push({
    id: "program",
    titleKey: "Client.Integration.Steps.Program",
    descriptionKey: "Client.Integration.Steps.WorkerProgramDescription",
    blocks: [
      {
        id: "program",
        language: "csharp",
        code: buildClientCredentialsProgram(clientConfig, options, scopes),
        fileName: "Program.cs",
        isDownloadable: true,
      },
    ],
    notes,
    warnings,
  });

  steps.push({
    id: "worker",
    titleKey: "Client.Integration.Steps.Worker",
    descriptionKey: "Client.Integration.Steps.WorkerDescription",
    blocks: [
      {
        id: "worker",
        language: "csharp",
        code: buildClientCredentialsWorker(),
        fileName: "ApiWorker.cs",
        isDownloadable: true,
      },
    ],
  });

  return { steps };
};

/** All blocks of a document joined together, for the "copy everything" action. */
export const flattenSnippetDocument = (document: SnippetDocument): string =>
  document.steps
    .flatMap((step) => step.blocks.map((block) => block.code))
    .join("\n\n");
